version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000 && python manage.py load_data
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MSQL_DATABASE: 'my_database'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql