# Generated by Django 3.1.4 on 2022-03-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Supervisors',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('date_of_graduation', models.DateField()),
                ('date_of_employment', models.DateField()),
                ('position', models.CharField(choices=[('FR', 'frontend'), ('SO', 'backend'), ('JR', 'Junior'), ('SR', 'Senior'), ('B', 'boss')], default='FR', max_length=255)),
                ('salary', models.IntegerField()),
                ('employee_code', models.CharField(blank=True, max_length=6, null=True)),
                ('supervisors', models.ManyToManyField(blank=True, to='employee.Supervisors')),
            ],
            options={
                'verbose_name_plural': 'Employee Records',
            },
        ),
    ]
