# Generated by Django 3.1.4 on 2022-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_of_upload', models.DateTimeField(auto_now_add=True)),
                ('number_of_employee_records_uploaded', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('errors', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_duplicate_entries', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Upload logs',
            },
        ),
    ]
